### ISSUE TITLE
Doesn't play nice with Before

### ISSUE THREAD

**Issue by milovanderlinden** [whitfin/it.each#5]
I have a before that is async and uses done. it-each is executed before the before function is done..

Here is my code:

```javascript
//During the test the env variable is set to test
process.env.NODE_ENV = 'test';

//Require the dev-dependencies
var chai = require('chai');
var chaiHttp = require('chai-http');
chai.use(chaiHttp);
var should = chai.should();
var fs = require('fs');
var app = require('../server');
var models = require('../models');
require('it-each')({ testPerIteration: true });
var fs = require('fs');
var Chance = require('chance');
var chance = new Chance();


var token = chance.guid();
var user;
var uoms;

describe('testing /api/unit', function(done) {
  before(function(done){
    var testuser = {
      name: chance.name(),
      email: chance.email(),
      token: token
    };
    user = new models.User.model(testuser);
    user.save(function(err, user, count) {
      user = user;
      fs.readFile('./test/assets/uom.json', 'utf8', function (err, data) {
        uoms = JSON.parse(data);
        done();
      });
    });
  });

  it.each(uoms, 'POST should return %s', ['code'], function(uom, done) {
    chai.request(app).
    post('/api/unit').
    set('x-access-token', token).
    send(uom).
    end(function(err, res) {
      var data = JSON.parse(res.text);
      res.should.be.json; // jshint ignore:line
      res.should.have.status(200);
      should.equal(data.code, uom.code);
      done();
    });
  });
});
```

And this is the error:
```javascript
node_modules/dot-notes/lib/dot.notes.js:57
        return tmp[keys[keys.length - 1]];
                  ^

TypeError: Cannot read property 'code' of undefined
    at Object.get (/data/Development/water-api/node_modules/dot-notes/lib/dot.notes.js:57:19)
    at Object.generateArgs (/data/Development/water-api/node_modules/it-each/lib/util.js:22:28)
    at /data/Development/water-api/node_modules/it-each/lib/it.each.js:21:56
    at Array.forEach (native)
    at Function.it.each (/data/Development/water-api/node_modules/it-each/lib/it.each.js:16:22)
    at Suite.<anonymous> (/data/Development/water-api/test/testUom.js:39:6)
    at Object.create (/data/Development/water-api/node_modules/mocha/lib/interfaces/common.js:114:19)
    at context.describe.context.context (/data/Development/water-api/node_modules/mocha/lib/interfaces/bdd.js:44:27)
    at Object.<anonymous> (/data/Development/water-api/test/testUom.js:22:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /data/Development/water-api/node_modules/mocha/lib/mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (/data/Development/water-api/node_modules/mocha/lib/mocha.js:219:14)
    at Mocha.run (/data/Development/water-api/node_modules/mocha/lib/mocha.js:487:10)
    at Object.<anonymous> (/data/Development/water-api/node_modules/mocha/bin/_mocha:459:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3

**Comment by whitfin** [comment]
This is actually default Mocha behaviour; your `it.each` is being read before the async behaviour of your before is complete. 

There's no way to work around this at this point, so I'm going to close this - it's just any annoyance of JS.
